# Define stages
stages:
  - deploy

deploy-to-github:
  stage: deploy
  script:
    - apk add --no-cache git
    - git config --global http.sslVerify false
    - git clone --branch main --single-branch https://package-distribution:$GITLAB_TOKEN@git.rsc-gitlab.elering.sise/rsc/it/nc-data-exchange.git repo
    - cd repo
    - git remote add github https://$GITHUB_TOKEN@$REPOSITORY
    - git push --force github main
  only:
    - main
  when: manual