# Define stages
stages:
  - deploy

deploy-to-github:
  stage: deploy
  script:
    - apk add --no-cache git
    - git config --global http.sslVerify false
    - git clone --bare https://package-distribution:$GITLAB_TOKEN@git.rsc-gitlab.elering.sise/rsc/it/nc-data-exchange.git repo
    - cd repo
    - git remote add github https://$GITHUB_TOKEN@github.com/$USERNAME/$REPOSITORY
    - git push --mirror github
  only:
    - main
  when: manual