[project]
name = "nc-data-exchange"
version = "0.2.0"
authors = [
  {name = "Martynas Karobcikas", email = "martynas.karobcikas@baltic-rcc.eud"}
]
description = "A package for building NetworkCode [NC] data exchange profiles"
readme = "README.md"
license = "MPL-2.0"
requires-python = ">=3.11"
dependencies = [
    "lxml>=6.1.0",
    "openpyxl>=3.1.5",
    "pandas>=3.0.2",
    "pydantic>=2.13.3",
    "pydantic-settings>=2.14.0",
    "pyshacl>=0.31.0",
    "rdflib>=7.6.0",
    "triplets>=0.0.17",
    "xmltodict>=1.0.4",
]
